spring:
  application:
    name: mybatis-sample
  profiles:
    default: local

server:
  port: ${SERVER_PORT:localhost}

mybatis:
  type-aliases-package: org.example.mybatissample.model.*
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-handlers-package: org.example.mybatissample.handler.typehandler

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:test}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: test