spring:
  application:
    name: mybatis-sample
  profiles:
    default: local

server:
  port: 8080

mybatis:
  type-aliases-package: org.example.mybatissample.model.*
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-handlers-package: org.example.mybatissample.handler.typehandler

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: test